menunav:
    inicio:
        icon: home
        descricao: Mural
        link: /
    cadastros:
        icon: folder-open-o
        descricao: Cadastros
        items:
            clientes:
                descricao: Clientes
                link: /cliente
            lotes:
                descricao: Lotes
                link: /lote
            empreendimentos:
                descricao: Empreendimentos
                link: /empreendimento
            corretores:
                descricao: Corretores
                link: /corretor
            usuarios:
                descricao: Usuários
                link: /usuario
    lancamentos:
        icon: exchange
        descricao: Lançamentos
        items:
            contrato:
                descricao: Contrato
                link: /contrato
    relatorios:
        icon: bar-chart-o
        descricao: Relatórios
        items:
            teste:
                descricao: Teste
                link: /relatorio/teste

pagination:
    limit: 10