menunav:
    inicio:
        descricao: Início
        link: /
    cadastros:
        descricao: Cadastros
        items:
            clientes:
                descricao: Clientes
                link: /cliente
            usuarios:
                descricao: Usuários
                link: /usuario
            corretores:
                descricao: Corretores
                link: /corretor
            empreendimentos:
                descricao: Empreendimentos
                link: /empreendimento
            lotes:
                descricao: Lotes
                link: /lote
    lancamentos:
        descricao: Lançamentos
        items:
            contrato:
                descricao: Contrato
                link: /contrato

pagination:
    limit: 10