menunav:
    cadastros:
        descricao: Cadastros
        items:
            clientes:
                descricao: Clientes
                link: /cliente
            usuarios:
                descricao: Usuários
                link: /usuario
            corretores:
                descricao: Corretores
                link: /corretor
            empreendimentos:
                descricao: Empreendimentos
                link: /empreendimento
    lancamentos:
        descricao: Lançamentos