inicio:
    method: get
    route: Home:index
    url: /
login:
    method: get
    route: Home:login
    url: /login
logar:
    method: post
    route: Home:logar
    url: /logar
logout:
    method: get
    route: Home:sair
    url: /sair

estados:
    method: get
    route: Home:estados
    url: /estados

cidades:
    method: get
    route: Home:cidades
    url: /cidades/:uf

#Rotas de cadastro de clientes
cliente:
    method: get
    route: Cliente:index
    url: /cliente

cliente_cadastro_pf:
    method: get
    route: Cliente:cadastroPf
    url: /cliente/cadastro/pf

cliente_edita_pf:
    method: get
    route: Cliente:editaPf
    url: /cliente/edita/pf/:id

cliente_edita_pj:
    method: get
    route: Cliente:editaPj
    url: /cliente/edita/pj/:id

cliente_cadastro_pj:
    method: get
    route: Cliente:cadastroPj
    url: /cliente/cadastro/pj

cliente_all:
    method: get
    route: Cliente:all
    url: /cliente/all(/:id)

cliente_acoes:
    method: post
    route: Cliente:acoes
    url: /cliente/acoes/:acao

cliente_busca:
    method: get
    route: Cliente:busca
    url: /cliente/busca/:id

cidades:
    method: get
    route: Cliente:cidades
    url: /cidades/:uf

salvar_pf:
    method: post
    route: Cliente:salvarPf
    url: /cliente/pf/salvar

#Rotas de cadastro de Empreendimentos
empreendimento:
    method: get
    route: Empreendimento:index
    url: /empreendimento

empreendimento_novo:
    method: post
    route: Empreendimento:novo
    url: /empreendimento/novo(/:id)

empreendimento_all:
    method: get
    route: Empreendimento:all
    url: /empreendimento/all(/:id)

empreendimento_acoes:
    method: post
    route: Empreendimento:acoes
    url: /empreendimento/acoes/:acao


#Rotas de cadastro de Usuários
usuario:
    method: get
    route: Usuario:index
    url: /usuario

usuario_all:
    method: get
    route: Usuario:all
    url: /usuario/all(/:id)

usuario_grupos:
    method: get
    route: Usuario:grupos
    url: /usuario/grupos(/:id)

usuario_novo:
    method: post
    route: Usuario:novo
    url: /usuario/novo(/:id)

usuario_acoes:
    method: post
    route: Usuario:acoes
    url: /usuario/acoes/:acao

#Rotas de cadastro de corretores
corretor:
    method: get
    route: Corretor:index
    url: /corretor

corretor_novo:
    method: get
    route: Corretor:novo
    url: /corretor/novo

corretor_all:
    method: get
    route: Corretor:all
    url: /corretor/all(/:id)

corretores:
    method: get
    route: Corretor:corretores
    url: /corretores

corretor_busca:
    method: get
    route: Corretor:busca
    url: /corretor/busca/:id

corretor_edita:
    method: get
    route: Corretor:edita
    url: /corretor/edita/:id

corretor_salvar:
    method: post
    route: Corretor:salvar
    url: /corretor/salvar

corretor_acoes:
    method: post
    route: Corretor:acoes
    url: /corretor/acoes/:acao

#Rotas de cadastro de Lotes
lote:
    method: get
    route: Lote:index
    url: /lote

lote_novo:
    method: post
    route: Lote:novo
    url: /lote/novo(/:id)

lote_all:
    method: get
    route: Lote:all
    url: /lote/all(/:id)

lote_acoes:
    method: post
    route: Lote:acoes
    url: /lote/acoes/:acao