inicio:
    method: get
    route: Home:index
    url: /
login:
    method: get
    route: Home:login
    url: /login
logar:
    method: post
    route: Home:logar
    url: /logar
logout:
    method: get
    route: Home:sair
    url: /sair

cliente:
    method: get
    route: Cliente:index
    url: /cliente

cliente_cadastro_pf:
    method: get
    route: Cliente:cadastroPf
    url: /cliente/cadastro/pf

cliente_edita_pf:
    method: get
    route: Cliente:editaPf
    url: /cliente/edita/pf/:id

cliente_cadastro_pj:
    method: get
    route: Cliente:cadastroPj
    url: /cliente/cadastro/pj

cliente_all:
    method: get
    route: Cliente:all
    url: /cliente/all(/:id)

cliente_busca:
    method: get
    route: Cliente:busca
    url: /cliente/busca/:id

cidades:
    method: get
    route: Cliente:cidades
    url: /cidades/:uf

salvar_pf:
    method: post
    route: Cliente:salvarPf
    url: /cliente/pf/salvar



usuario:
    method: get
    route: Usuario:index
    url: /usuario

usuario_all:
    method: get
    route: Usuario:all
    url: /usuario/all(/:id)

usuario_novo:
    method: post
    route: Usuario:novo
    url: /usuario/novo(/:id)

usuario_acoes:
    method: post
    route: Usuario:acoes
    url: /usuario/acoes/:acao

corretor:
    method: get
    route: Corretor:index
    url: /corretor

corretor_novo:
    method: get
    route: Corretor:novo
    url: /corretor/novo