inicio:
    method: get
    route: Home:index
    url: /
login:
    method: get
    route: Home:login
    url: /login
logar:
    method: post
    route: Home:logar
    url: /logar
logout:
    method: get
    route: Home:sair
    url: /sair

estados:
    method: get
    route: Home:estados
    url: /estados

cidades:
    method: get
    route: Home:cidades
    url: /cidades/:uf

#Rotas de cadastro de clientes
cliente:
    method: get
    route: Cliente:index
    url: /cliente

cliente_cadastro_pf:
    method: get
    route: Cliente:cadastroPf
    url: /cliente/cadastro/pf

cliente_edita_pf:
    method: get
    route: Cliente:editaPf
    url: /cliente/edita/pf/:id

cliente_by_cpf_cnpj:
    method: get
    route: Cliente:cpfCnpj
    url: /cliente/cpf_cnpj/:cpf_cnpj

cliente_edita_pj:
    method: get
    route: Cliente:editaPj
    url: /cliente/edita/pj/:id

cliente_cadastro_pj:
    method: get
    route: Cliente:cadastroPj
    url: /cliente/cadastro/pj

cliente_all:
    method: get
    route: Cliente:all
    url: /cliente/all(/:id)

cliente_acoes:
    method: post
    route: Cliente:acoes
    url: /cliente/acoes/:acao

cliente_busca:
    method: get
    route: Cliente:busca
    url: /cliente/busca/:id

cliente_by_query:
    method: get
    route: Cliente:query
    url: /cliente/:query

get_clientes:
    method: get
    route: Cliente:getClientes
    url: /cliente/get/all

get_cnae:
    method: get
    route: Cliente:getCnae
    url: /cliente/cnae

cidades:
    method: get
    route: Cliente:cidades
    url: /cidades/:uf

salvar_pf:
    method: post
    route: Cliente:salvarPf
    url: /cliente/pf/salvar

#Rotas de cadastro de Empreendimentos
empreendimento:
    method: get
    route: Empreendimento:index
    url: /empreendimento

empreendimento_novo:
    method: post
    route: Empreendimento:novo
    url: /empreendimento/novo(/:id)

empreendimento_all:
    method: get
    route: Empreendimento:all
    url: /empreendimento/all(/:id)

empreendimento_one:
    method: get
    route: Empreendimento:one
    url: /empreendimento/one/:id

empreendimento_acoes:
    method: post
    route: Empreendimento:acoes
    url: /empreendimento/acoes/:acao


#Rotas de cadastro de Usuários
usuario:
    method: get
    route: Usuario:index
    url: /usuario

usuario_all:
    method: get
    route: Usuario:all
    url: /usuario/all(/:id)

usuario_grupos:
    method: get
    route: Usuario:grupos
    url: /usuario/grupos(/:id)

usuario_novo:
    method: post
    route: Usuario:novo
    url: /usuario/novo(/:id)

usuario_acoes:
    method: post
    route: Usuario:acoes
    url: /usuario/acoes/:acao

minha_conta:
    method: get
    route: Usuario:minhaConta
    url: /minha-conta

minha_conta_update:
    method: post
    route: Usuario:minhaContaUpdate
    url: /minha-conta/update

#Rotas de cadastro de corretores
corretor:
    method: get
    route: Corretor:index
    url: /corretor

corretor_novo:
    method: get
    route: Corretor:novo
    url: /corretor/novo

corretor_all:
    method: get
    route: Corretor:all
    url: /corretor/all(/:id)

corretores:
    method: get
    route: Corretor:corretores
    url: /corretores

corretor_by_cpf_cnpj:
    method: get
    route: Corretor:cpfCnpj
    url: /corretor/cpf_cnpj/:cpf_cnp

corretor_busca:
    method: get
    route: Corretor:busca
    url: /corretor/busca/:id

corretor_by_query:
    method: get
    route: Corretor:query
    url: /corretor/:query

corretor_edita:
    method: get
    route: Corretor:edita
    url: /corretor/edita/:id

corretor_salvar:
    method: post
    route: Corretor:salvar
    url: /corretor/salvar

corretor_acoes:
    method: post
    route: Corretor:acoes
    url: /corretor/acoes/:acao

#Rotas de cadastro de Lotes
lote:
    method: get
    route: Lote:index
    url: /lote

lotes_corretor:
    method: get
    route: Lote:lotesCorretor
    url: /corretor-lotes

lote_novo:
    method: post
    route: Lote:novo
    url: /lote/novo(/:id)

lote_all:
    method: get
    route: Lote:all
    url: /lote/all(/:id)

lote_empreendimento:
    method: get
    route: Lote:lotes
    url: /lote/lotes/:id

lote_acoes:
    method: post
    route: Lote:acoes
    url: /lote/acoes/:acao

#Rotas de contrato
contrato:
    method: get
    route: Contrato:index
    url: /contrato

contrato_parcelas:
    method: post
    route: Contrato:parcelas
    url: /contrato/parcelas

contrato_novo:
    method: post
    route: Contrato:novo
    url: /contrato/novo

contrato_all:
    method: get
    route: Contrato:all
    url: /contrato/all(/:id)

contrato_acoes:
    method: post
    route: Contrato:acoes
    url: /contrato/acoes/:acao

contrato_get:
    method: get
    route: Contrato:getEdit
    url: /contrato/get/:id